### ISSUE TITLE
Visual bug with Trees

### ISSUE THREAD

**Issue by TetsuyaGR** [chairclr/TerraAngel#20]
When you create a new world with the seed `celebrationmk10` the trees appear green in TerraAngel
![terraangel](https://user-images.githubusercontent.com/48888784/196306325-00cb2341-5c41-4641-b6bd-544806fc7967.png)
Whereas in Vanilla, they appear rainbow-colorful
![vanilla](https://user-images.githubusercontent.com/48888784/196306358-38760c15-de9f-47d6-b358-c7fac8336581.png)

**Comment by CEO-Chair** [comment]
Thanks for the report, I'll fix this soon™️, but not a priority right now.
