### ISSUE TITLE
fast start gives error "not a got repository"

### ISSUE THREAD

**Issue by brausefisch** [chairclr/TerraAngel#44]
I downloaded everything correctly as far as I can tell but when i try to use fast start i get said error message, so it doesnt find the git repository

**Comment by brausefisch** [comment]
Turns out there are missing files in the download, is there a way to send a screenshot of the files created? Its missing the .git file and the src file

**Comment by CEO-Chair** [comment]
You must use `git clone` with the recursive flag set, as stated in the installation guide. You can also try restarting your computer and re-cloning the repository.

**Comment by ZataraTMM** [comment]
Having the same problem, i did use git clone and recursive, restarted, quickly getting "not a git " in cmd.  tried multiple times
