### ISSUE TITLE
Fast start closes without doing anything

### ISSUE THREAD

**Issue by Grimm590** [chairclr/TerraAngel#48]
When i run the fast start, it doesnt do anything, ive tried running it in the cmd and it says "The system cannot find the path specified." so i think that its got something to do with the fact that the program has some kind of trouble running these commands:

git submodule update --remote --recursive > NUL
dotnet build TerraAngelSetup\TerraAngelSetup\TerraAngelSetup.csproj -c=Release > NUL

if i try to run each command individually it says exactly nothing, as if it was run succesfully (i assume nothing would print out if there was no problem). ive tried other solutions to this problem that i saw on other posted issues that had the same problem but none of them worked. im suspecting that the problem might be the fact that my terraria directory isnt installed on the C drive but thats only a speculation and one without any ground since i barely understand how to speak code . i can provide any other necessary details just ask for them.

**Comment by CEO-Chair** [comment]
Open cmd and cd to the directory that your TerraAngel clone is installed in, then run fast_start.bat from cmd

**Comment by Grimm590** [comment]
> Open cmd and cd to the directory that your TerraAngel clone is installed in, then run fast_start.bat from cmd

Ive already done that

**Comment by TruePowerSyao** [comment]
Same issue
