### ISSUE TITLE
Crashing whenever I do certain things

### ISSUE THREAD

**Issue by Devonsnow514** [chairclr/TerraAngel#50]
If I hover over any item it crashes my game. Joining a server also crashes my game

**Comment by Devonsnow514** [comment]
@CEO-Chair

**Comment by CEO-Chair** [comment]
Is there any message associated with the crash?

**Comment by CEO-Chair** [comment]
Also upload your `client-crashlog.txt`, which is located in the same directory as the TerraAngel executable.

**Comment by CEO-Chair** [comment]
Also don't mention me. I will receive a notification regardless of whether or not you mention me, and mentioning me will not cause my response to be any faster.

**Comment by Devonsnow514** [comment]
Sorry for mentioning you. Im sending the file right now

**Comment by Devonsnow514** [comment]
![image](https://user-images.githubusercontent.com/83614401/235375083-fc2c5b37-6037-47f4-b636-1a36a73f0355.png)

**Comment by Devonsnow514** [comment]
[client-crashlog.txt](https://github.com/CEO-Chair/TerraAngel/files/11362256/client-crashlog.txt)

**Comment by Devonsnow514** [comment]
> 

No there is not any message associated with the crash. It just freezes, Then Closes. It only happens while hovering over a item for 30 seconds after loading into a wold

**Comment by CEO-Chair** [comment]
This seems to be an error with your Terraria content folder. Try verifying your Terraria files through steam.
Right click on Terraria in steam, go to properties, go to Local Files, and press Verify integrity of game files.

**Comment by Devonsnow514** [comment]
I just did that, I was getting a error saying to copy my Terraria "Content Folder" To where the client was installed, But I didnt have a  Content folder so i am currently reinstalling terraria.

**Comment by Devonsnow514** [comment]
I verified my game files and Im still crashing after I hover over a item

**Comment by Devonsnow514** [comment]
I fixed the crashing, The game still crashes If I hover over any items/slots and after 30 seconds. There is no crash log anymore

**Comment by steviegt6** [comment]
Can we lock this? Conversation is too heated, LBTM.

**Comment by Devonsnow514** [comment]
idk lol. my game keeps crashing If I hover over a item/slot and If i dont hover over a slot it crashes afre a minute. (only if i got terrangel installed) it can be locked idrc

**Comment by Devonsnow514** [comment]
getting another error ofc..
[console.txt](https://github.com/CEO-Chair/TerraAngel/files/11362318/console.txt)

**Comment by Devonsnow514** [comment]
I reinstalled terraria and terraangel, My game still crashes
