### ISSUE TITLE
There is a problem with screen expansion on a 14 inch monitor.

### ISSUE THREAD

**Issue by Babecum** [chairclr/TerraAngel#64]
There was a problem with screen expansion on a 14 inch monitor. the game image doesn't fit correctly on the screen, even when I set it to 1920x1080 it still looks like 1024x768. help with this please!!!!!!!!

**Comment by Babecum** [comment]
on the recording it looks like this

**Comment by Babecum** [comment]
I would share the recording, but I’m too lazy to compress the file somehow

**Comment by chairclr** [comment]
See pinned issue
